name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Generate tag
      id: generate-tag
      run: echo "::set-output name=tag::$(date +%s)"

    - name: Modify Dockerfile
      run: ./modify_dockerfile.sh

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        tags: masaishi2001/diffusers-docker-with-jupyter:${{ steps.generate-tag.outputs.tag }}
        push: true
